# Generated by Django 3.2.25 on 2026-04-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='_data_payload',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='text',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='_content',
            field=models.TextField(default='{}'),
        ),
    ]
