# Generated by Django 3.2.25 on 2026-04-07 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnSecurityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('datasets', models.JSONField(blank=True, default=list)),
                ('columns', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domains', models.ManyToManyField(blank=True, to='users.Domain')),
                ('subdomains', models.ManyToManyField(blank=True, to='users.SubDomain')),
                ('users', models.ManyToManyField(blank=True, related_name='csgs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
