# Generated by Django 3.2.25 on 2026-04-07 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowSecurityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('_filters', models.TextField(blank=True, default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domains', models.ManyToManyField(blank=True, to='users.Domain')),
                ('subdomains', models.ManyToManyField(blank=True, to='users.SubDomain')),
                ('users', models.ManyToManyField(blank=True, related_name='rsgs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
